---
resources:
- name: dispatch-ui
  type: git
  source:
    uri: https://github.com/pzmrzy/dispatch-ui.git
    branch: release

- name: version-ui
  type: semver
  source:
    initial_version: 0.0.1
    bucket: ((s3-ci-bucket-name))
    key: dispatch-ui-version
    region_name: ((s3-ci-bucket-region-name))
    access_key_id: ((s3-ci-bucket-access-key))
    secret_access_key: ((s3-ci-bucket-secret-key))

# - name: gh-release
#   type: github-release
#   source:
#     owner: dispatchframework
#     repository: dispatch-ui
#     access_token: ((github-access-token))

jobs:
- name: major
  public: true
  serial_groups: [version]
  plan:
  - get: version
    resource: version-ui
    params: {bump: major}
  - put: version
    resource: version-ui
    params: {file: version/version}

- name: minor
  public: true
  serial_groups: [version]
  plan:
  - get: version
    resource: version-ui
    params: {bump: minor}
  - put: version
    resource: version-ui
    params: {file: version/version}

- name: patch
  public: true
  serial_groups: [version]
  plan:
  - get: version
    resource: version-ui
    params: {bump: patch}
  - put: version
    resource: version-ui
    params: {file: version/version}

- name: release
  public: true
  plan:
  - get: version
    resource: version-ui
    trigger: true
  - get: dispatch-ui
    resource:  dispatch-ui
  - task: prepare-version
    file: dispatch-ui/ci/tasks/prepare-version.yml
  - task: build-ui-binaries
    file: dispatch-ui/ci/tasks/build-bundle.yml
  # - put: gh-release
  #   params:
  #     name: release-context/tag
  #     tag: release-context/tag
  #     commitish: release-context/branch
  #     globs:
  #     - dispatch-ui-binaries/dispatch-ui.tar.gz