---
platform: linux

image_resource:
  type: docker-image
  source: {repository: node}

inputs:
- name: dispatch-ui
  path: src/github.com/dispatchframework/dispatch-ui

outputs:
- name: dispatch-ui-binaries

run:
  path: /bin/bash
  args:
  - -c
  - |
    set -e -u -x

    export GOPATH=$PWD
    cd $GOPATH/src/github.com/dispatchframework/dispatch-ui
    npm install
    npm run build
    mv build/* $GOPATH/dispatch-ui-binaries/
